server:
  port: 5000

backbase:
  my_secret: ${MY_SECRET:my yaml secret}

spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
  packages-to-exclude: com.backbase.interview.course.exception.handler