server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    enable:
      jvm: true
  logging:
    level:
      ROOT: INFO

spring:
  application:
    name: Courses API
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
  packages-to-exclude: com.andre.course.exception.handler